%YAML:1.0

#########2020-03-01 flight3_2020-03-01.bag#########
imu_topic: "/imu/data"    #/dji_sdk/imu,  /mavros/imu/data_raw

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2          # accelerometer measurement noise standard deviation.
gyr_n: 0.05         # gyroscope measurement noise standard deviation.
acc_w: 0.002         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 4.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.805    # gravity magnitude

# Extrinsic parameter from Lidar to IMU(imu^T_lidar), rotation(degree) translation(m)
# Euler angle (z-y-x)
EI2L_RX: 0
EI2L_RY: 0
EI2L_RZ: 0
EI2L_TX: -0.013
EI2L_TY: 0.065
EI2L_TZ: 0.075
   
# window size for initialization
#INITIAL_STRUCTURE_SIZE: 10

#lidar parameters
lineRes: 0.3
planeRes: 0.6

#unsynchronization parameters
estimate_lidar_camera_time_difference: 0
align_camera_time: 0
lidar_td: -0.004                     #time delay of lidar
lidar_camera_time_difference: -0.016

#vio pointcloud
##vlp16 measurement range is +15 ~ -15 degree
limited_upward_angle: 15
limited_downward_angle: -15 #vertical
limited_CW_angle: 35
limited_CCW_angle: -35 #yaw
